name: Automated tests
on:
  push

jobs:
  tests: 
    runs-on: ubuntu latests


    steps:
      - name: Checkout repository
        uses: action/checkout@v3 
      - name: setup Python
      uses: action/setup-python@v4
      with:
        python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: 